### ISSUE TITLE
Werid bug during initiation

### ISSUE THREAD

**Issue by pawelorzech** [bruno1308/thecrimshelper#6]
I did install requirements. Added things in config. But it fails. Anything I could try and do differently?

```
INFO     Getting home page
INFO     Getting player info and logging in...
SUCCESS  Logged in successfully!
INFO     Getting home page, now logged
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main(sys.argv)
  File "main.py", line 101, in main
    login()
  File "main.py", line 28, in login
    playerInfo = parser.find("script", {"name": "user"}).content
AttributeError: 'NoneType' object has no attribute 'contents'
```

When I commented out this part with user content:

```
INFO     Getting home page
INFO     Getting player info and logging in...
SUCCESS  Logged in successfully!
INFO     Getting home page, now logged
HEADER   ------------------- STARTING ACTION 1 -------------------
INFO     Entering robbery...
DEBUG    Getting robbery hash
ERROR    Error while getting robbery hash: 'NoneType' object has no attribute 'parent'
ERROR    Error while entering robbery:cannot concatenate 'str' and 'NoneType' objects
ERROR    Program stopped because of list index out of range
INFO     Program ran for 0.0553357833333 minutes
ERROR    Terminate program

```

**Comment by mattos123** [comment]
got the same problem ...

**Comment by bruno1308** [comment]
Sorry folks, I'm not supporting the bot anymore, they must have changed some content on their page. Pull requests are welcome though.

**Comment by zeus1921** [comment]
pls update
